// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package api

import (
	context "context"

	request "github.com/ksysoev/opengate/pkg/core/request"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// HandleRequest provides a mock function with given fields: ctx, req
func (_m *MockService) HandleRequest(ctx context.Context, req *request.Request) (*request.Response, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for HandleRequest")
	}

	var r0 *request.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.Request) (*request.Response, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.Request) *request.Response); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_HandleRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleRequest'
type MockService_HandleRequest_Call struct {
	*mock.Call
}

// HandleRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.Request
func (_e *MockService_Expecter) HandleRequest(ctx interface{}, req interface{}) *MockService_HandleRequest_Call {
	return &MockService_HandleRequest_Call{Call: _e.mock.On("HandleRequest", ctx, req)}
}

func (_c *MockService_HandleRequest_Call) Run(run func(ctx context.Context, req *request.Request)) *MockService_HandleRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*request.Request))
	})
	return _c
}

func (_c *MockService_HandleRequest_Call) Return(_a0 *request.Response, _a1 error) *MockService_HandleRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_HandleRequest_Call) RunAndReturn(run func(context.Context, *request.Request) (*request.Response, error)) *MockService_HandleRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
