// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package middleware

import (
	context "context"

	request "github.com/ksysoev/opengate/pkg/core/request"
	mock "github.com/stretchr/testify/mock"
)

// MockMiddleware is an autogenerated mock type for the Middleware type
type MockMiddleware struct {
	mock.Mock
}

type MockMiddleware_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMiddleware) EXPECT() *MockMiddleware_Expecter {
	return &MockMiddleware_Expecter{mock: &_m.Mock}
}

// Process provides a mock function with given fields: ctx, req, next
func (_m *MockMiddleware) Process(ctx context.Context, req *request.Request, next HandlerFunc) (*request.Response, error) {
	ret := _m.Called(ctx, req, next)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 *request.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.Request, HandlerFunc) (*request.Response, error)); ok {
		return rf(ctx, req, next)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.Request, HandlerFunc) *request.Response); ok {
		r0 = rf(ctx, req, next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.Request, HandlerFunc) error); ok {
		r1 = rf(ctx, req, next)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMiddleware_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockMiddleware_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.Request
//   - next HandlerFunc
func (_e *MockMiddleware_Expecter) Process(ctx interface{}, req interface{}, next interface{}) *MockMiddleware_Process_Call {
	return &MockMiddleware_Process_Call{Call: _e.mock.On("Process", ctx, req, next)}
}

func (_c *MockMiddleware_Process_Call) Run(run func(ctx context.Context, req *request.Request, next HandlerFunc)) *MockMiddleware_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*request.Request), args[2].(HandlerFunc))
	})
	return _c
}

func (_c *MockMiddleware_Process_Call) Return(_a0 *request.Response, _a1 error) *MockMiddleware_Process_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMiddleware_Process_Call) RunAndReturn(run func(context.Context, *request.Request, HandlerFunc) (*request.Response, error)) *MockMiddleware_Process_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMiddleware creates a new instance of MockMiddleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMiddleware(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMiddleware {
	mock := &MockMiddleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
