// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package core

import (
	context "context"

	request "github.com/ksysoev/opengate/pkg/core/request"
	mock "github.com/stretchr/testify/mock"

	route "github.com/ksysoev/opengate/pkg/core/route"
)

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx, req, rt
func (_m *MockHandler) Handle(ctx context.Context, req *request.Request, rt *route.Route) (*request.Response, error) {
	ret := _m.Called(ctx, req, rt)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 *request.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.Request, *route.Route) (*request.Response, error)); ok {
		return rf(ctx, req, rt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.Request, *route.Route) *request.Response); ok {
		r0 = rf(ctx, req, rt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.Request, *route.Route) error); ok {
		r1 = rf(ctx, req, rt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.Request
//   - rt *route.Route
func (_e *MockHandler_Expecter) Handle(ctx interface{}, req interface{}, rt interface{}) *MockHandler_Handle_Call {
	return &MockHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, req, rt)}
}

func (_c *MockHandler_Handle_Call) Run(run func(ctx context.Context, req *request.Request, rt *route.Route)) *MockHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*request.Request), args[2].(*route.Route))
	})
	return _c
}

func (_c *MockHandler_Handle_Call) Return(_a0 *request.Response, _a1 error) *MockHandler_Handle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHandler_Handle_Call) RunAndReturn(run func(context.Context, *request.Request, *route.Route) (*request.Response, error)) *MockHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
