// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package core

import mock "github.com/stretchr/testify/mock"

// MockRuntime is an autogenerated mock type for the Runtime type
type MockRuntime struct {
	mock.Mock
}

type MockRuntime_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRuntime) EXPECT() *MockRuntime_Expecter {
	return &MockRuntime_Expecter{mock: &_m.Mock}
}

// GetHTTPClient provides a mock function with no fields
func (_m *MockRuntime) GetHTTPClient() HTTPClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHTTPClient")
	}

	var r0 HTTPClient
	if rf, ok := ret.Get(0).(func() HTTPClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(HTTPClient)
		}
	}

	return r0
}

// MockRuntime_GetHTTPClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHTTPClient'
type MockRuntime_GetHTTPClient_Call struct {
	*mock.Call
}

// GetHTTPClient is a helper method to define mock.On call
func (_e *MockRuntime_Expecter) GetHTTPClient() *MockRuntime_GetHTTPClient_Call {
	return &MockRuntime_GetHTTPClient_Call{Call: _e.mock.On("GetHTTPClient")}
}

func (_c *MockRuntime_GetHTTPClient_Call) Run(run func()) *MockRuntime_GetHTTPClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRuntime_GetHTTPClient_Call) Return(_a0 HTTPClient) *MockRuntime_GetHTTPClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRuntime_GetHTTPClient_Call) RunAndReturn(run func() HTTPClient) *MockRuntime_GetHTTPClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRuntime creates a new instance of MockRuntime. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRuntime(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRuntime {
	mock := &MockRuntime{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
