// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package core

import (
	context "context"

	request "github.com/ksysoev/opengate/pkg/core/request"
	mock "github.com/stretchr/testify/mock"
)

// MockRuntime is an autogenerated mock type for the Runtime type
type MockRuntime struct {
	mock.Mock
}

type MockRuntime_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRuntime) EXPECT() *MockRuntime_Expecter {
	return &MockRuntime_Expecter{mock: &_m.Mock}
}

// SendRequest provides a mock function with given fields: ctx, req
func (_m *MockRuntime) SendRequest(ctx context.Context, req *request.Request) (*request.Response, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SendRequest")
	}

	var r0 *request.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.Request) (*request.Response, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.Request) *request.Response); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRuntime_SendRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRequest'
type MockRuntime_SendRequest_Call struct {
	*mock.Call
}

// SendRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req *request.Request
func (_e *MockRuntime_Expecter) SendRequest(ctx interface{}, req interface{}) *MockRuntime_SendRequest_Call {
	return &MockRuntime_SendRequest_Call{Call: _e.mock.On("SendRequest", ctx, req)}
}

func (_c *MockRuntime_SendRequest_Call) Run(run func(ctx context.Context, req *request.Request)) *MockRuntime_SendRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*request.Request))
	})
	return _c
}

func (_c *MockRuntime_SendRequest_Call) Return(_a0 *request.Response, _a1 error) *MockRuntime_SendRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRuntime_SendRequest_Call) RunAndReturn(run func(context.Context, *request.Request) (*request.Response, error)) *MockRuntime_SendRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRuntime creates a new instance of MockRuntime. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRuntime(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRuntime {
	mock := &MockRuntime{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
