// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package core

import (
	route "github.com/ksysoev/opengate/pkg/core/route"
	mock "github.com/stretchr/testify/mock"
)

// MockspecParser is an autogenerated mock type for the specParser type
type MockspecParser struct {
	mock.Mock
}

type MockspecParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockspecParser) EXPECT() *MockspecParser_Expecter {
	return &MockspecParser_Expecter{mock: &_m.Mock}
}

// ParseFile provides a mock function with given fields: filePath
func (_m *MockspecParser) ParseFile(filePath string) ([]route.Route, error) {
	ret := _m.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for ParseFile")
	}

	var r0 []route.Route
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]route.Route, error)); ok {
		return rf(filePath)
	}
	if rf, ok := ret.Get(0).(func(string) []route.Route); ok {
		r0 = rf(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]route.Route)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(filePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockspecParser_ParseFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseFile'
type MockspecParser_ParseFile_Call struct {
	*mock.Call
}

// ParseFile is a helper method to define mock.On call
//   - filePath string
func (_e *MockspecParser_Expecter) ParseFile(filePath interface{}) *MockspecParser_ParseFile_Call {
	return &MockspecParser_ParseFile_Call{Call: _e.mock.On("ParseFile", filePath)}
}

func (_c *MockspecParser_ParseFile_Call) Run(run func(filePath string)) *MockspecParser_ParseFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockspecParser_ParseFile_Call) Return(_a0 []route.Route, _a1 error) *MockspecParser_ParseFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockspecParser_ParseFile_Call) RunAndReturn(run func(string) ([]route.Route, error)) *MockspecParser_ParseFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockspecParser creates a new instance of MockspecParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockspecParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockspecParser {
	mock := &MockspecParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
